### ISSUE TITLE
Keep getting panic on no such file or directory with .tmp file

### ISSUE THREAD

**Issue by ryanfantus** [robbiew/fetch16c#1]
Trying to run this and getting the following error:

```
bbs@montereybbs:/opt/bbs/files/16c/fetch16c$ ./fetch16c -years 10 -path ..
Ok, going back 10 years from 2022:
Path exists...
Starting the application...
../2012... Creating directory...
https://16colo.rs/archive/2012/cph-26ar.zip... Downloading...
ext:  .zip
panic: open ../2012/cph-26ar.zip.tmp: no such file or directory

goroutine 1 [running]:
main.callAPI()
        /home/robbiew/go/src/github.com/robbiew/fetch16c/main.go:136 +0x103a
main.main()
        /home/robbiew/go/src/github.com/robbiew/fetch16c/main.go:309 +0x575
```

**Comment by robbiew** [comment]
Sorry so late to respond! Something has changed with endpoints it seems. Gotta dive in

**Comment by robbiew** [comment]
OK, this is probably a year too late @ryanfantus, but I re-wrote this program from the ground-up. 
Tested on Ubuntu 22.04 x64 and Windows 10, the program successfully downloads and unpacks ZIP and LHA files. 
Binary files are available in RELEASES.
